name: Test and Deploy
on:
  - push

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Make
      run: sudo apt-get install make -y

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create env
      run: make create-environment

    - name: Install Requirements
      run: make requirements

    - name: Run Security Checks
      run: make security-test

    - name: Run Static Code Checks
      run: make run-flake

    - name: Run Coverage Checks
      run: make check-coverage


  run-unit-tests:
    runs-on: ubuntu-latest
    needs: run-checks

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create env
        run: make create-environment

      - name: Install Requirements
        run: make requirements

      - name: Run Unit Tests
        run: make unit-test
